### PR TITLE
Fixing http adapter to allow HTTPS connections via HTTP

### PR DESCRIPTION
**Pull request by zcei**
Allows accessing HTTPS APIs via a configured HTTP proxy

### CODE REVIEW

**Review by Khaledgarbaya — APPROVED** [review]
LGTM 👍

**Comment by mrispoli24** [comment]
This has broken our deployments on two of our applications. We are continuing to receive errors here in heroku despite disabling caching and updating the package. We could use some advice here since all of our deploys are failing since this branch was deleted, it shouldn't have affected anything but this error continues to stop our builds.

*Update*

To anyone that stumbles upon this as we have... the fix for us to deploy is to switch to the active LTS version of node which is 8.11.0 right now. This causes failures in all versions above this, though we are still trying to investigate exactly why.

**Comment by mrispoli24** [comment]
Yet one more update, we were able to update node versions again but had to update our package.json file to `"contentful": "^6.1.1"` it seems having the up carrot with a lower version number wouldn't update the package to the latest. Also trying to update with npm in the command line wouldn't work either. Not sure how changing node versions caused this to update the way that it did.

**Comment by axe312ger** [comment]
@mrispoli24 Sorry for the trouble! Was clearly my mistake, I released a fresh v4.6.5 which points to the correct axios version for v4. This will never happen again :)

**Pull request merged**
